# Generated by Django 2.0.1 on 2018-01-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180130_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blog'),
        ),
    ]
