# Generated by Django 2.0.1 on 2018-02-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postmodel_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
